name: CI/CD Pipeline for Java Maven Project with Minikube and Java 17

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or your project’s specific version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' as the distribution for JDK 17

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: mvn test

      # Step 6: Set up Minikube
      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.26.0'  # Specify the Kubernetes version if needed
          driver: docker  # Use Docker as the driver for Minikube

      # Step 7: Set up Docker for Minikube
      - name: Set up Docker for Minikube
        run: eval $(minikube docker-env)

      # Step 8: Build Docker Image with Minikube's Docker
      - name: Build Docker Image
        run: docker build -t dissertation:${{ github.sha }} .

      # Step 9: Load the Docker image into Minikube
      - name: Load Docker Image into Minikube
        run: minikube image load dissertation:${{ github.sha }}

      # Step 10: Generate Kubernetes YAML files using Helm
      - name: Generate Kubernetes YAML files
        run: helm template dissertation helm/dissertation --set image.repository=dissertation --set image.tag=${{ github.sha }} > k8s-manifests.yaml

      # Step 11: Deploy to Minikube using Helm
      - name: Deploy to Minikube
        run: |
          helm upgrade --install dissertation helm/dissertation --set image.repository=dissertation --set image.tag=${{ github.sha }}

      # Step 12: Test service URLs
      - name: Test service URLs
        run: |
            minikube service list
            minikube service ${{ github.event.release.name }}-dissertation --url   
